version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    post_checkout:
      - git fetch --unshallow
      # Use -W builds for PRs
      - |
        if (echo $READTHEDOCS_VERSION_NAME | grep -E '^[0-9]+$' >/dev/null); then
            export SPHINXOPTS="-W"
        fi
      - env
    pre_build:
      - env

python:
  install:
    - requirements: docs/requirements.txt
    - path: .
      extra_requirements:
        - doc
    - path: wrapper/
